# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# Ideally, the pipeline_api_key is only used on dev, test environments.
# However, for the sake of the project it assumes that this API key
# will be used across all environments and furthermore is a test key
# therefore does not require security.
shared:
  pipeline_api_key: G5mZccexXgchNkAYOBlQ


# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1168332181b3c26e282ff35bd94f396c14a2013caf32891c53135cee5ef8b1ea8740518e2cc51dc4e8d4e2bea7a3289b8af8d30c8ac0d8e5a690a093bda8cdee

test:
  secret_key_base: 628ce9b230c981ddc50c0fd0b25a4768e1d82d9418b4c2c0e4e0dbfd5b8174e598e4c5eda0fd03407a01d333785b77e43803829b556401e8971566a1ebfce9a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
